FROM node:10

# appユーザ追加 & npmの最新版DL
RUN useradd --user-group --create-home -u 1000 -o --shell /bin/false node-app \                                                                                    
    && groupmod -g 1000 -o node-app \                                                                                                                              
    && npm install --global npm@6.4.1 yarn

# 環境変数を引継ぎ
ARG SRC_DIR 
ARG NODE_HOME

# hostからpackage.jsonをコピー
ADD $SRC_DIR/package.json $NODE_HOME
ADD $SRC_DIR/yarn.lock $NODE_HOME


# appユーザに切替
USER node-app
WORKDIR $NODE_HOME

# yarn導入後パッケージ導入
RUN yarn install --dev 
